In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LogisticRegression
# from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB, ComplementNB
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
import pickle

In [6]:
from pre_processing import X_train,X_test,y_train,y_test


In [7]:
X_train

array([[ 0.69943451, -1.07529066,  1.16287262, ..., -0.95685724,
        -0.05465445, -0.69178857],
       [-1.42972642,  0.92998111, -0.85993942, ...,  1.75481825,
         0.83921027, -0.69178857],
       [ 0.69943451,  0.92998111, -0.85993942, ..., -0.2943413 ,
        -0.20980257, -0.69178857],
       ...,
       [ 0.69943451, -1.07529066,  1.16287262, ...,  0.56441933,
        -1.66784227,  1.44552836],
       [ 0.69943451,  0.92998111, -0.85993942, ..., -0.5765381 ,
        -0.21156562,  1.44552836],
       [ 0.69943451, -1.07529066,  1.16287262, ...,  1.24899379,
        -0.34555717, -0.69178857]])

In [8]:
y_test

status_binary
86               1
75               0
127              1
47               1
97               0
..             ...
249              0
251              0
99               0
280              0
295              0

[89 rows x 1 columns]

In [10]:
X_test

array([[ 0.69943451,  0.92998111, -0.85993942, ..., -0.42441044,
        -0.9079691 , -0.69178857],
       [-1.42972642,  0.92998111, -0.85993942, ...,  0.10803636,
         0.84978855, -0.69178857],
       [-1.42972642, -1.07529066,  1.16287262, ..., -1.29914447,
        -0.66643169, -0.69178857],
       ...,
       [ 0.69943451,  0.92998111, -0.85993942, ..., -1.71749553,
        -0.47778568, -0.69178857],
       [-1.42972642,  0.92998111, -0.85993942, ..., -0.95685724,
        -0.86212988, -0.69178857],
       [ 0.69943451, -1.07529066,  1.16287262, ..., -0.50047427,
        -0.48483787, -0.69178857]])

In [11]:
y_train

status_binary
158              0
189              0
67               1
78               1
175              0
..             ...
199              1
155              0
156              1
133              1
245              0

[207 rows x 1 columns]

In [13]:
lr_model = LogisticRegression(solver = 'newton-cholesky')
lr_model.fit(X_train,y_train['status_binary'])

LogisticRegression(solver='newton-cholesky')

In [15]:
lr_testscore = lr_model.score(X_test,y_test['status_binary'])
lr_testscore


0.8426966292134831

In [16]:
y_test

status_binary
86               1
75               0
127              1
47               1
97               0
..             ...
249              0
251              0
99               0
280              0
295              0

[89 rows x 1 columns]

In [17]:
y_pred = lr_model.predict(X_test)
y_pred

array([1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0])

In [19]:
# create classifier object
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors =2)



In [20]:
# Train the classifier using the training data 
knn.fit(X_train,y_train['status_binary'])


KNeighborsClassifier(n_neighbors=2)

In [21]:
# Estimate the accuracy of the classifier on future data,using the test data
knn.score(X_test,y_test['status_binary'])


0.7415730337078652

In [22]:
y_test

status_binary
86               1
75               0
127              1
47               1
97               0
..             ...
249              0
251              0
99               0
280              0
295              0

[89 rows x 1 columns]

In [23]:
y_pred_knn=knn.predict(X_test)
y_pred_knn


array([1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0,
       0])

In [26]:
rfc = RandomForestClassifier(n_estimators = 300,random_state = 100)
rfc.fit(X_train,y_train['status_binary'])


RandomForestClassifier(n_estimators=300, random_state=100)

In [27]:
rfc.score(X_test,y_test['status_binary'])

0.9325842696629213

In [28]:
# score_rfc = rfc.score(x_train,y_train['status_bianry'])
# score_rfc


In [30]:
rfc_predict = lr_model.predict(X_test)
rfc_predicted_dict = {'predicted_values': rfc_predict,'original_values':y_test['status_binary']}
# creating new dataframe
op = pd.DataFrame(rfc_predicted_dict)
op[op['predicted_values']!=op['original_values']]


predicted_values  original_values
92                  0                1
219                 1                0
165                 1                0
131                 0                1
135                 0                1
124                 0                1
202                 0                1
153                 0                1
94                  0                1
154                 0                1
193                 0                1
121                 0                1
150                 0                1
178                 0                1

In [32]:
nbc = GaussianNB()
nbc.fit(X_train,y_train['status_binary'])


GaussianNB()

In [33]:
nbc.score(X_test,y_test['status_binary'])


0.449438202247191

In [35]:
X_test[0]

array([ 0.69943451,  0.92998111, -0.85993942, -0.24806947, -0.63138629,
       -0.96673649,  1.05463022,  0.79367579, -0.29859554, -0.121278  ,
       -0.14028192, -0.42441044, -0.9079691 , -0.69178857])

In [36]:
# Dumping the model object
pickle.dump(rfc,open('model.pkl','wb'))


In [37]:
pickle.dump(lr_model,open('lr_model.pkl','wb'))


In [38]:
print(confusion_matrix(y_test['status_binary'],rfc_predict))


[[44  2]
 [12 31]]


In [43]:
pip install -r requirements.txt

Note: you may need to restart the kernel to use updated packages.
